[project]
name = "evocomp"
version = "0.1.0"
authors = [{ name = "Lex Miin", email = "hello@lexunix.me" }]
description = "Evolutionary algorithms"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy>=1.26.0",
]

[project.optional-dependencies]
visual = [
  "matplotlib>=3.8.0",
  "openpyxl>=3.1.2",
  "pandas>=2.1.1",
]

[dependency-groups]
dev = [
  "ruff>=0.9.0",
  "scipy>=1.11.4",
  "ty>=0.0.64",
]

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["UP019", "I001"]
ignore = ["E741", "E203"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true
exclude = [
  './examples/**/*.py',
  './README.md'
]

[tool.ruff.lint.isort]
force-single-line = true

[tool.uv.dependency-groups]
dev = { requires-python = ">=3.11" }
